#!/bin/bash

touch hello.sh
nano hello.sh



echo "hello world"



chmod +x hello.sh
./hello.sh



name="Vinay"
echo $name



read -p "Enter Name: " name
echo "Hello $name"






age=10

if [ age -eq 18 ]
then 
    echo " minor"
else
then 
    echo " adult"




count=1

while [ $count -le 5]
do 
  echo $count
  ((count++))
done





function()
{
    echo "hello world"
}




# Basic script for port scanner


#!/bin/bash

# Usage: ./scanner.sh <IP_ADDRESS> <START_PORT> <END_PORT>

host=$1
start_port=$2
end_port=$3

if [ -z "$host" ] || [ -z "$start_port" ] || [ -z "$end_port" ]; then
    echo "Usage: $0 <IP> <start_port> <end_port>"
    exit 1
fi

echo "Scanning $host from port $start_port to $end_port..."

for ((port=start_port; port<=end_port; port++)); do
    # Attempt connection; timeout 1 second prevents hanging on closed ports
    timeout 1 bash -c "echo >/dev/tcp/$host/$port" 2>/dev/null
    if [ $? -eq 0 ]; then
        echo "Port $port is open"
    fi
done   
